//! Autogenerated weights for `pns_registrar::price_oracle`.
//!
//! Source: `./target/release/paseo-node benchmark pallet
//!   --chain=dev --pallet=pns_registrar::price_oracle --extrinsic='*'
//!   --steps=20 --repeat=5 --output=...` on 2026-04-21.
//! Host: AMD Ryzen 9 5900HX. Regenerate with the same invocation when
//! the pallet's extrinsic surface or storage shape changes.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pns_registrar::price_oracle`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> super::price_oracle::WeightInfo for SubstrateWeight<T> {
    /// Storage: `PnsPriceOracle::ExchangeRate` (r:0 w:1)
    /// Proof: `PnsPriceOracle::ExchangeRate` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    fn set_exchange_rate() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 6_516_000 picoseconds.
        Weight::from_parts(7_434_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `PnsPriceOracle::BasePrice` (r:0 w:1)
    /// Proof: `PnsPriceOracle::BasePrice` (`max_values`: Some(1), `max_size`: Some(176), added: 671, mode: `MaxEncodedLen`)
    fn set_base_price() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_040_000 picoseconds.
        Weight::from_parts(8_128_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// Storage: `PnsPriceOracle::RentPrice` (r:0 w:1)
    /// Proof: `PnsPriceOracle::RentPrice` (`max_values`: Some(1), `max_size`: Some(176), added: 671, mode: `MaxEncodedLen`)
    fn set_rent_price() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 7_167_000 picoseconds.
        Weight::from_parts(8_153_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
