//! Autogenerated weights for `pns_registrar::registrar`.
//!
//! Source: `./target/release/paseo-node benchmark pallet
//!   --pallet=pns_registrar::registrar --extrinsic='*'
//!   --steps=10 --repeat=5 --output=...` on 2026-04-21.
//! Host: AMD Ryzen 9 5900HX. Regenerate with the same invocation when
//! the pallet's extrinsic surface or storage shape changes.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pns_registrar::registrar`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> super::registrar::WeightInfo for SubstrateWeight<T> {
    fn add_reserved() -> Weight {
        // Minimum execution time: 11_676_000 picoseconds.
        Weight::from_parts(12_786_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    fn remove_reserved() -> Weight {
        // Minimum execution time: 11_244_000 picoseconds.
        Weight::from_parts(12_180_000, 0)
            .saturating_add(Weight::from_parts(0, 0))
            .saturating_add(T::DbWeight::get().writes(1))
    }
    /// The range of component `s` is `[1, 10]`.
    fn register(_s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1076`
        //  Estimated: `7046`
        // Minimum execution time: 171_735_000 picoseconds.
        Weight::from_parts(187_715_047, 0)
            .saturating_add(Weight::from_parts(0, 7046))
            .saturating_add(T::DbWeight::get().reads(16))
            .saturating_add(T::DbWeight::get().writes(14))
    }
    fn renew() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `988`
        //  Estimated: `3593`
        // Minimum execution time: 137_340_000 picoseconds.
        Weight::from_parts(142_224_000, 0)
            .saturating_add(Weight::from_parts(0, 3593))
            .saturating_add(T::DbWeight::get().reads(7))
            .saturating_add(T::DbWeight::get().writes(5))
    }
    fn transfer() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1357`
        //  Estimated: `11646`
        // Minimum execution time: 174_241_000 picoseconds.
        Weight::from_parts(182_207_000, 0)
            .saturating_add(Weight::from_parts(0, 11646))
            .saturating_add(T::DbWeight::get().reads(16))
            .saturating_add(T::DbWeight::get().writes(11))
    }
    fn release_name() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1099`
        //  Estimated: `8094`
        // Minimum execution time: 114_943_000 picoseconds.
        Weight::from_parts(122_112_000, 0)
            .saturating_add(Weight::from_parts(0, 8094))
            .saturating_add(T::DbWeight::get().reads(10))
            .saturating_add(T::DbWeight::get().writes(13))
    }
    /// The range of component `s` is `[1, 32]`.
    fn offer_subdomain(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `762`
        //  Estimated: `4227`
        // Minimum execution time: 51_332_000 picoseconds.
        Weight::from_parts(54_313_449, 0)
            .saturating_add(Weight::from_parts(0, 4227))
            // Standard Error: 926
            .saturating_add(Weight::from_parts(707, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn accept_subdomain() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `969`
        //  Estimated: `4434`
        // Minimum execution time: 63_912_000 picoseconds.
        Weight::from_parts(66_805_000, 0)
            .saturating_add(Weight::from_parts(0, 4434))
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(8))
    }
    fn reject_subdomain() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `358`
        //  Estimated: `3642`
        // Minimum execution time: 22_970_000 picoseconds.
        Weight::from_parts(24_986_000, 0)
            .saturating_add(Weight::from_parts(0, 3642))
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    fn revoke_subdomain() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `833`
        //  Estimated: `4298`
        // Minimum execution time: 39_579_000 picoseconds.
        Weight::from_parts(42_064_000, 0)
            .saturating_add(Weight::from_parts(0, 4298))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn release_subdomain() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `855`
        //  Estimated: `6795`
        // Minimum execution time: 62_229_000 picoseconds.
        Weight::from_parts(65_218_000, 0)
            .saturating_add(Weight::from_parts(0, 6795))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(10))
    }
    fn accept_offered_name() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `430`
        //  Estimated: `3585`
        // Minimum execution time: 39_532_000 picoseconds.
        Weight::from_parts(42_278_000, 0)
            .saturating_add(Weight::from_parts(0, 3585))
            .saturating_add(T::DbWeight::get().reads(6))
            .saturating_add(T::DbWeight::get().writes(4))
    }
    fn cleanup() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1281`
        //  Estimated: `8094`
        // Minimum execution time: 164_530_000 picoseconds.
        Weight::from_parts(177_103_000, 0)
            .saturating_add(Weight::from_parts(0, 8094))
            .saturating_add(T::DbWeight::get().reads(14))
            .saturating_add(T::DbWeight::get().writes(14))
    }
}
