//! Autogenerated weights for `pns_marketplace`.
//!
//! Source: `./target/release/paseo-node benchmark pallet
//!   --pallet=pns_marketplace --extrinsic='*' --steps=10 --repeat=5
//!   --output=...` on 2026-04-21.
//! Host: AMD Ryzen 9 5900HX. Regenerate with the same invocation when
//! the pallet's extrinsic surface or storage shape changes.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pns_marketplace`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> crate::WeightInfo for SubstrateWeight<T> {
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Storage: `PnsRegistrar::OwnerToPrimaryName` (r:1 w:0)
    /// Storage: `PnsMarketplace::Listings` (r:1 w:1)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Storage: `PnsMarketplace::ListingDeposits` (r:0 w:1)
    fn create_listing() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `314`
        //  Estimated: `3569`
        // Minimum execution time: 87_639_000 picoseconds.
        Weight::from_parts(111_536_000, 0)
            .saturating_add(Weight::from_parts(0, 3569))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `PnsRegistrar::OwnerToPrimaryName` (r:1 w:0)
    /// Storage: `PnsMarketplace::Listings` (r:1 w:1)
    /// Storage: `PnsMarketplace::ListingDeposits` (r:1 w:1)
    /// Storage: `Balances::Holds` (r:1 w:1)
    fn cancel_listing() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `552`
        //  Estimated: `3569`
        // Minimum execution time: 83_900_000 picoseconds.
        Weight::from_parts(103_343_000, 0)
            .saturating_add(Weight::from_parts(0, 3569))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
    }
    /// Storage: `PnsMarketplace::Listings` (r:1 w:1)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Storage: `PnsNft::Tokens` (r:1 w:1)
    /// Storage: `PnsRegistrar::RegistrarInfos` (r:1 w:0)
    /// Storage: `System::Account` (r:2 w:2)
    /// Storage: `PnsPriceOracle::BasePrice` (r:1 w:0)
    /// Storage: `PnsRegistrar::CleanupDeposit` (r:1 w:1)
    /// Storage: `Balances::Holds` (r:2 w:2)
    /// Storage: `PnsMarketplace::ListingDeposits` (r:1 w:1)
    /// Storage: `PnsRegistrar::OwnerToPrimaryName` (r:2 w:2)
    /// Storage: `PnsRegistry::AccountToSubnames` (r:1 w:0)
    /// Storage: `PnsRegistry::RuntimeOrigin` (r:1 w:0)
    /// Storage: `PnsRegistry::SubNames` (r:1 w:0)
    /// Storage: `PnsResolvers::Records` (r:3 w:1)
    /// Storage: `PnsResolvers::RecordCount` (r:1 w:1)
    /// Storage: `PnsNft::TokensByOwner` (r:0 w:2)
    fn buy_name() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2017`
        //  Estimated: `11646`
        // Minimum execution time: 459_770_000 picoseconds.
        Weight::from_parts(565_777_000, 0)
            .saturating_add(Weight::from_parts(0, 11646))
            .saturating_add(T::DbWeight::get().reads(20))
            .saturating_add(T::DbWeight::get().writes(14))
    }
    /// Storage: `PnsMarketplace::Listings` (r:1 w:1)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Storage: `PnsMarketplace::ListingDeposits` (r:1 w:1)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Storage: `System::Account` (r:1 w:1)
    fn cleanup_listing() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `369`
        //  Estimated: `3593`
        // Minimum execution time: 121_862_000 picoseconds.
        Weight::from_parts(184_281_000, 0)
            .saturating_add(Weight::from_parts(0, 3593))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
    }
}
