//! Autogenerated weights for `pns_resolvers::resolvers`.
//!
//! Source: `./target/release/paseo-node benchmark pallet
//!   --pallet=pns_resolvers::resolvers --extrinsic='*'
//!   --steps=10 --repeat=5 --output=...` on 2026-04-21.
//! Host: AMD Ryzen 9 5900HX. Regenerate with the same invocation when
//! the pallet's extrinsic surface or storage shape changes.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use polkadot_sdk::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pns_resolvers::resolvers`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: polkadot_sdk::frame_system::Config> super::resolvers::WeightInfo for SubstrateWeight<T> {
    /// Storage: `PnsNft::Tokens` (r:1 w:0)
    /// Storage: `PnsRegistrar::RegistrarInfos` (r:1 w:0)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Storage: `PnsResolvers::Records` (r:1 w:1)
    /// Storage: `PnsResolvers::RecordCount` (r:1 w:1)
    /// The range of component `s` is `[0, 1024]`.
    fn set_record(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `588`
        //  Estimated: `4542`
        // Minimum execution time: 53_921_000 picoseconds.
        Weight::from_parts(76_772_616, 0)
            .saturating_add(Weight::from_parts(0, 4542))
            // Standard Error: 373
            .saturating_add(Weight::from_parts(7_845, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    /// Storage: `PnsNft::Tokens` (r:1 w:0)
    /// Storage: `PnsRegistrar::RegistrarInfos` (r:1 w:0)
    /// Storage: `Timestamp::Now` (r:1 w:0)
    /// Storage: `PnsResolvers::Texts` (r:0 w:1)
    /// The range of component `s` is `[0, 1024]`.
    fn set_text(s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `450`
        //  Estimated: `3915`
        // Minimum execution time: 39_795_000 picoseconds.
        Weight::from_parts(60_716_943, 0)
            .saturating_add(Weight::from_parts(0, 3915))
            // Standard Error: 289
            .saturating_add(Weight::from_parts(5_365, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
